services:
  d3lta_dsn:
    build:
      context: ./D3lta
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces
    command: sleep infinity
  python_dsn:
    image: python:3.13
    volumes:
      - .:/workspaces
    command: sleep infinity